### ISSUE TITLE
Chapter 13 - No module named braces, embed_video and memcache_status

### ISSUE THREAD

**Issue by bright00** [PacktPublishing/Django-2-by-Example#13]
There are modules missings:

  File "/home/action/educa/courses/views.py", line 12, in <module>
    from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
ImportError: No module named 'braces'
Also no modules 'embed_video', and 'memcache_status'

How to fix this?

**Comment by bright00** [comment]
/educa $ pip3 install django-braces
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: django-braces in /usr/local/lib/python2.7/dist-packages (1.13.0)
/educa $ python3 manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x75cbe540>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/action/educa/educa/urls.py", line 19, in <module>
    from courses.views import CourseListView
  File "/home/action/educa/courses/views.py", line 12, in <module>
    from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
ImportError: No module named 'brace'

What is going wrong here?

**Comment by salah-cpu** [comment]
hello
am put : 
- pip3 install django-braces

  (((((  from braces.views import SelectRelatesMixin )))
ImportError: cannot import name 'SelectRelatesMixin' from 'braces.views' (C:\Users\SalahEddine\Anaconda3\envs\myDjangenv\lib\site-packages\braces\views\__init__.py)


help please !!

**Comment by AjayNiven** [comment]
found any solution for this?
